### ISSUE TITLE
投票：点阵图形还是矢量图形？

### ISSUE THREAD

**Issue by Gsllchb** [Gsllchb/PyLf#10]
目前我遇到了一个两难的局面：继续走点阵图形这条路还是走矢量图形的路线？

### 优势
* 点阵图形是目前所采用的方案，较为成熟
* 便于对字形做扰动

### 劣势
* 对打印不友好，易于出现锯齿等缺陷，若想达到视网膜级别的打印效果，无论是内存占用还是生成的图片都会异常巨大

### 优势
* 打印效果优异

### 劣势
* 不易于对笔画做扰动处理

我觉得对字形进行扰动的选择是对的，但我也觉得对矢量图形的路线貌似更自然也更优雅。__你们觉得呢？__

请在下面通过点赞的方式进行投票。欢迎发表自己的看法！

**Comment by Gsllchb** [comment]
点阵图形：喜欢我的请给我点赞💗💗💗

**Comment by Gsllchb** [comment]
喜欢矢量图形的朋友在哪里！

**Comment by YYTB** [comment]
确实两难，前面我觉得矢量好，但是写字的人不可能每个字每次下笔角度都一样

**Comment by YYTB** [comment]
所以扰动是必须的

**Comment by Gsllchb** [comment]
对啊

YYTB <notifications@github.com> 于 2019年2月4日周一 23:38写道：

**Comment by 14790897** [comment]
可以根据点阵图生成矢量图
