### ISSUE TITLE
是不是少了些参数？？？？

### ISSUE THREAD

**Issue by planzq** [Gsllchb/PyLf#3]
是不是少了些参数？
想调整字间距咋做？

**Comment by Gsllchb** [comment]
并没有。你看`pylf.handwrite`的docstring，里面不但有调节字间距的参数，还有大量的其它参数以及高级参数。示例代码中仅仅只使用能使代码运行的最少的参数。

**Comment by planzq** [comment]
感觉word_spacing_sigma font_size_sigma line_spacing_sigma 调整一下 没啥反应呢？？？

**Comment by Gsllchb** [comment]
你应该调节word_spacing。带sigma后缀的都是调节相应参数随机性强弱的。

**Comment by planzq** [comment]
嗯 调整字间距的 我已经看明白了 就是想调整下带sigma的 让字间距行距都能随机调整 但是感觉没啥反应

**Comment by Gsllchb** [comment]
你把值设大一点，越大随机性越强。

**Comment by planzq** [comment]
sigma的取值范围是多少？

**Comment by Gsllchb** [comment]
从-∞～+∞，绝对值越大随机性越强。只要文档里没限制的，你就大胆去做。。。

**Comment by planzq** [comment]
谢谢 我都调整了 现在效果很棒 谢谢

**Comment by Gsllchb** [comment]
不客气
