### ISSUE TITLE
图片打印出来没有打印字清晰，怎么处理？？？

### ISSUE THREAD

**Issue by planzq** [Gsllchb/PyLf#4]
用打印机打出来，感觉有点点阵的感觉，没有直接打字清晰，咋处理？

**Comment by Gsllchb** [comment]
你可以尝试使用更大分辨率的背景图，更大的font_size；另外试一下更好的打印机。
但是依旧可能不如word文档打印的效果，提高打印质量是我今后版本的改进目标之一。

**Comment by planzq** [comment]
谢谢 明白了

**Comment by Gsllchb** [comment]
点阵主要来源于打印灰色的区域，这是为了抗锯齿生成的过渡区域。 但是黑白喷墨打印机在打印灰色时是用纯黑和背景白混合形成的。所以，依我之见，可以试试更高dpi的打印机或者彩色打印（你要是不差钱的话）。
