### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by YYTB** [Gsllchb/PyLf#6]
# Feature

本人门外汉，正在努力入门python，提几条不成熟的建议
1. 建议找一种办法将字体点阵化读取，输出的时候适当抖动，这样即使两个一样的字放在一起也不会看上去完全一样。
2. 建议引入随机分布错别字接口。
3. 能否考虑输出矢量pdf文件。（估计这个可能要完全重构吧，当没说吧。）
可惜学艺不精，文科生学这个着实费劲，真希望能贡献一点力量

**Comment by Gsllchb** [comment]
谢谢你的建议！
1. 其实在现在的版本中已经使用了你所说的算法，同一个字其实不一样的。有相关参数可以调节，在使用默认参数下，我选择了保守的策略，即模拟一个字体非常工整的人的认真书写。
2. 我觉得在输入的字符串中就应该会人为的（无论是故意还是无意）含有错别字。至于对人书写错误进行模拟方面的功能，我会认真考虑的。
2. 实现输出PDF有两种方式：
    * 最简单的就是直接将生成图片粘贴到PDF中，这其实和几张图片文件没有本质区别；这种如果的确需要的话，我可以在后续版本中加入此功能。
    * 黑入字体，对字体做随机化修改，然后在随机化排版；这如你所说近乎完全重构，而且其中一些问题非常棘手；这个我会考虑，但是近期不会考虑。

**Comment by Gsllchb** [comment]
非常感谢你提的宝贵建议！

1. 对于涂改这个问题，我推荐目前最好的方式是在打印的结果上做人工修改。至于加入涂改功能，首先每个人的涂改方式不一样；其次如果是自动化涂改的话，可能涉及语义分析，如果是人工标记涂改位置，就需使用标记语言（创建一种或使用已存在的）而不仅仅是纯文本（plain text）。这个问题我要看其他用户的反馈，以此做出是否加入此功能的决定。

2. `alpha`参数就是用于使同一个字不一样的。

3. 这个建议非常宝贵。我会在后续版本（可能在v2.0，也可能在v1.x，主要出于接口后向兼容性的考虑）中加入“周期性模板”（其中具体的细节我们可以深入讨论）的。目前而言，我有一权宜之计，以一个白色且alpha通道为0的图为背景输入`handwrite`，然后将所要的背景图与生成图片合并。假如你写不出来，联系我，我可以帮你写一份示例代码；如果你写出来了，欢迎为本项目写一份示例代码，放在`example`文件夹中并发出`pull request`。

（下次请记得给issue打上label，如果是不同的主题应该分成几个issue）

**Comment by YYTB** [comment]
昨天尽折腾网络了，我想你明白的。

我不太理解意思，不知道这个alpha通道为0的图片是自己用图片软件做好还是调用Image，如果是后者的话还没有研究过。

如果这样做的话，后面是不是又涉及到裁剪粘贴？这也有些麻烦，因为算裁剪面积又够呛，而且我在参数中普遍设置了一定的行距抖动，万一没算好裁剪面积，搞不好就把剪刀下在了某行文字的中间。

我打包了背景图发你gmail，如果真的有空写，第0页顶上的那些会议时间、主持人、记录人之类的信息就不用写了，省得麻烦。代码就没上，别辣你的眼睛，搅乱了你的思路，哈哈。

此致，新春快乐。

**Comment by Gsllchb** [comment]
新春快乐！
不好意思上次我没有考虑清楚，你奇偶页换的不仅仅是背景还有box参数，这个通过后期合并图片是无法解决的。
我已经决定在下一个版本v1.1.x加入此功能。

我先做个小调查:
你觉得在奇偶页更换时除了背景图和box参数改动外还会修改哪些参数？

**Comment by YYTB** [comment]
looking forward to it!

除了背景图和box我也暂时没想到有其他需要改的参数。本来我想说奇数偶数页的页码都在外侧，但是其实也是跟box有关。

另外，今天又折腾了一上午，本来想搞定`is_half_char`这个参数的用法，奈何循环写了不老少，效率是降低了，问题却没解决。感觉handwrite调用参数是一锤子买卖，而判断`is_half_char`又得逐个字符匹配，所以实在没辙了，只好腆着脸再来问聪明的作者：

> 您老有现成的范例么？
最好把Return这个API也示范一下，感觉放着现成的API不用，反而用`for num in range(0, len(images))`来循环存储绘图有点傻

顺便也建议如能更新example，可否考虑使用尽可能多的参数，毕竟对我这种初学者来说做减法要比加法简单一些。

**Comment by YYTB** [comment]
抱歉，写完上一条忽然想起来是不是可以参考你的is_end_char来写is_half_char。咋这么笨呢。
我的vultr 又被ban了，淡定，淡定。

**Comment by Gsllchb** [comment]
1. 页码这东西人工手写就好了，也没多少。当然了你也可以在生成的图片上调用Pillow(本库目前基于此库开发)的API来写上页码。

2. 返回值类型是list，如何遍历list我觉得任何一个Python入门教程都会提。

3. 谢谢你的建议，我以后多用参数。

4. box不能随机化，否则会整体平移的。另外box仅仅是限定所写内容每一个字平均位置的范围，每个字的具体位置会在平均位置的基础上随机化。

**Comment by Gsllchb** [comment]
is_end_char和is_half_char是要把函数作为实参传进去的，要是你不了解的话就用默认值吧。 gsllchb 邮箱：gsllchb@gmail.com 签名由 网易邮箱大师 定制 在2018年02月16日 13:28，YYTB 写道： 抱歉，写完上一条忽然想起来是不是可以参考你的is_end_char来写is_half_char。咋这么笨呢。 我的vultr 又被ban了，淡定，淡定。 — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by Gsllchb** [comment]
这个feature我已经实现得差不多了。
现在有一个问题：奇偶页的背景图片的大小`size`不一定是相同的。你觉得需要自动把背景图的大小调整到一致`size`的功能吗？
