### ISSUE TITLE
希望能支持axidraw

### ISSUE THREAD

**Issue by planzq** [Gsllchb/PyLf#7]
## Feature

axidraw这个画图机器人网上很多。由于普通打印机智能打印一张一张纸，不能打印整本的笔记本，但是axidraw可以，而且还有笔的压痕，强烈建议加入axidraw支持

**Comment by Gsllchb** [comment]
谢谢你的建议。
支持axidraw的问题可以归结为支持输出矢量图形的问题。这个问题我考虑过，也有其他人反馈过。
然而本库使用的是处理点阵图形的技术方案，将其改为矢量图形的技术方案无异于完全重构整个软件。其次普通打印机比类似于axidraw这样`矢量`输出的打印设备更为普及，因此短期内我不会考虑加入对矢量图形的支持。

**Comment by Gsllchb** [comment]
对于模拟效果而言，我相信使用矢量图形是比使用点阵图形处理更理想的技术方案。
