### ISSUE TITLE
字体参数传入一个列表比较好，为了更像人写的

### ISSUE THREAD

**Issue by shmilyoo** [Gsllchb/PyLf#8]
alpha和字体大小等扰动，我都试了一下，alpha大了点，字就飞了，小了效果几乎没有。
我觉得还是随机选择几个相似的手写字体比较好。 font参数传入一个列表，在_draw_text函数中每个字随机使用一个字体，这样是不是更加真实一点。

**Comment by Gsllchb** [comment]
首先，我也觉得现在的扰动算法存在问题。我打算在v2.0.0开发新的扰动算法。实际上，我打算在v2.0.0进行一次大更新，不仅仅是扰动算法的更新。为了能够与目前的打印设备更好的配合并获得以假乱真的打印效果，我将重新审视所有算法。

其次，我添加扰动算法的初衷是为了让每次“手写”同一个字会有不同的字形。我并不觉得随机选择字体能根本上解决这个问题。因为字体集合是有限的，如果你手写同一个字的次数足够多，你总能找到两个相同的字形。此外，我觉得“相似”的字体不会很好找。

**Comment by shmilyoo** [comment]
你说的有道理，还是得找一个治本的方法。
对于一个汉字，如果能够对每一个笔画进行变化就好了。
[你提到的矢量图形更为理想](https://github.com/Gsllchb/PyLf/issues/7#issuecomment-367559629)我也很赞同，也在想办法从这方面来琢磨。

**Comment by Gsllchb** [comment]
使用矢量图形的方案还有一点问题需要注意：
当黑进字体，对笔画进行修改的时候，会不会侵犯到字体作者的著作权？


shmilyoo <notifications@github.com> 于 2018年6月7日周四 11:02写道：

**Comment by shmilyoo** [comment]
我还想讨论下，现在写字机器人普遍存在着写成轮廓字而不是单线字的问题，单线汉字字体也非常有限， @Gsllchb 有没有想过生成矢量单线汉字呢

**Comment by shmilyoo** [comment]
@Gsllchb 是的，我了解。现有中文单线字体非常少，最好的方法当然是根据ttf字体来生成单线字体。ttf字体还可以根据用户自己的批量手写字来进行学习生成。相关技术和算法我也感兴趣。
不好意思回复迟了。持续关注，关闭issue了:blush:

**Comment by Gsllchb** [comment]
没事～
字体作者的著作权问题还是要考虑。要是侵犯到他人著作权，算法的效果再好都没用。
你可以看看另一个打开的issue。里面我和另一个人有讨论用机器学习的方法生成个性化字体的方案。

**Comment by Gsllchb** [comment]
欢迎加入[gitter](https://gitter.im/Python-PyLf/PyLf)参与讨论：）
