### ISSUE TITLE
以字体为单位的变形

### ISSUE THREAD

**Issue by B1ue-Sky** [Gsllchb/PyLf#9]
是否有可能引入字体的形变，使得高频率的字符相邻出现时显得更真实？
一种可能的方法也许是对字体先进行变形，再随机使用其中的字形？

进一步的，能否通过输入，学习出字体，从而解除对字体文件的依赖？

[huaji]也许会成为有趣的中文验证码生成/识别库？[/huaji]

**Comment by Gsllchb** [comment]
现在字体是有形变的。你要是觉得不够明显，可以调大alpha。

不过现在的扰动算法的确还不够好，存在缺陷。我看到有论文讲用机器学习生成手写字体的。

可以。北大已经有研究用机器学习的方法根据你写的字生成专属字体。不过需要你事先写一些字去训练模型。

中文验证码生成器不是我开发这个库的目标。即使可能可以用于这个用途。

**Comment by Gsllchb** [comment]
我并不打算在这个库中使用机器学习。我打算使用传统算法的技术路线。
如果我要是用机器学习的技术路线的话，我会另外开发一个库。

**Comment by Gsllchb** [comment]
欢迎加入[gitter](https://gitter.im/Python-PyLf/PyLf)参与讨论：）
